name: Release CI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: x86
            output: Bin/Release (lite)

          - platform: x64
            output: Bin/x64/Release (lite)

          - platform: ARM64EC
            output: Bin/ARM64EC/Release (lite)

    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - uses: microsoft/setup-msbuild@v2

      - name: Build
        shell: pwsh
        run: |
          msbuild TrafficMonitor_Lite.sln `
            /m `
            /p:Configuration="Release (lite)" `
            /p:Platform="${{ matrix.platform }}" `
            /p:PlatformToolset=v143

      - uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD_HHmmss
          utcOffset: "+08:00"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}_${{ steps.current-time.outputs.formattedTime }}_TrafficMonitor
          path: |
            ${{ matrix.output }}/TrafficMonitor.exe
            ${{ matrix.output }}/*.dll

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}_${{ steps.current-time.outputs.formattedTime }}_pdb
          path: |
            ${{ matrix.output }}/*.pdb
